apiVersion: v1
kind: Service
metadata:
  name: nexus3
spec:
  selector:                  
    name: nexus3
#  portalIP: 172.30.136.123   
  ports:
  - nodePort: 0
    port: 8081               
    protocol: TCP
    targetPort: 8081          
